import Joi from "joi";

export default {
  buscarSaveDocumento: Joi.object().keys({
    aux3: Joi.string().required(),
  }),
  cargarDiasPotencia: Joi.object().keys({
    ucp: Joi.string().required(),
  }),
  buscarVersioneSesion: Joi.object().keys({
    nombre: Joi.string().required(),
  }),
  agregarVersionSesion: Joi.object().keys({
    fecha: Joi.string().required(),
    ucp: Joi.string().required(),
    fechainicio: Joi.string().required(),
    fechafin: Joi.string().required(),
    tipodatos: Joi.string().required(),
    tendencia: Joi.string().required(),
    dias: Joi.string().required(),
    edicionfiltro: Joi.string().required(),
    edicionperiodo: Joi.string().required(),
    ediciontexto: Joi.string().required(),
    edicionfecha: Joi.string().required(),
    edicionsuma: Joi.string().required(),
    nombre: Joi.string().required(),
    version: Joi.string().required(),
    usuario: Joi.string().required(),
    p1_diario: Joi.string().required(),
    p2_diario: Joi.string().required(),
    p3_diario: Joi.string().required(),
    p4_diario: Joi.string().required(),
    p5_diario: Joi.string().required(),
    p6_diario: Joi.string().required(),
    p7_diario: Joi.string().required(),
    p8_diario: Joi.string().required(),
    p9_diario: Joi.string().required(),
    p10_diario: Joi.string().required(),
    p11_diario: Joi.string().required(),
    p12_diario: Joi.string().required(),
    p13_diario: Joi.string().required(),
    p14_diario: Joi.string().required(),
    p15_diario: Joi.string().required(),
    p16_diario: Joi.string().required(),
    p17_diario: Joi.string().required(),
    p18_diario: Joi.string().required(),
    p19_diario: Joi.string().required(),
    p20_diario: Joi.string().required(),
    p21_diario: Joi.string().required(),
    p22_diario: Joi.string().required(),
    p23_diario: Joi.string().required(),
    p24_diario: Joi.string().required(),
    nombrearchivo: Joi.string().required(),
    cargaindustrial: Joi.string().required(),
  }),
  agregarDatosPronosticoxSesion: Joi.object().keys({
    codsesion: Joi.string().required(),
    check_f: Joi.string().required(),
    fecha: Joi.string().required(),
    p1: Joi.string().required(),
    p2: Joi.string().required(),
    p3: Joi.string().required(),
    p4: Joi.string().required(),
    p5: Joi.string().required(),
    p6: Joi.string().required(),
    p7: Joi.string().required(),
    p8: Joi.string().required(),
    p9: Joi.string().required(),
    p10: Joi.string().required(),
    p11: Joi.string().required(),
    p12: Joi.string().required(),
    p13: Joi.string().required(),
    p14: Joi.string().required(),
    p15: Joi.string().required(),
    p16: Joi.string().required(),
    p17: Joi.string().required(),
    p18: Joi.string().required(),
    p19: Joi.string().required(),
    p20: Joi.string().required(),
    p21: Joi.string().required(),
    p22: Joi.string().required(),
    p23: Joi.string().required(),
    p24: Joi.string().required(),
    observacion: Joi.string().required(),
    tipo: Joi.string().required(),
  }),
  buscarDiaFestivo: Joi.object().keys({
    fecha: Joi.string().required(),
    ucp: Joi.string().required(),
  }),
  buscarPotenciaDia: Joi.object().keys({
    ucp: Joi.string().required(),
    dia: Joi.number().required(),
  }),
  cargarPeriodosxUCPDesdeFecha: Joi.object().keys({
    ucp: Joi.string().required(),
    fechaInicio: Joi.string().required(),
  }),
};
